# Generated by Django 3.1.1 on 2020-10-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=30)),
                ('option2', models.CharField(max_length=30)),
                ('option3', models.CharField(max_length=30)),
                ('count1', models.IntegerField(default=0)),
                ('count2', models.IntegerField(default=0)),
                ('count3', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='questions_choices',
        ),
        migrations.DeleteModel(
            name='questions_model',
        ),
    ]
